#!/bin/bash

for ttt in test_*.py
do
  out=${ttt%.*}.out
  ref=${ttt%.*}.ref
  python $ttt &>$out
  diff $ref $out
  if [[ $? -eq 0 ]]
  then
      echo "$ttt passed"
      rm $out
  else
      echo "$ttt failed"
  fi
done
